export declare const HomeIcon: () => import("react/jsx-runtime").JSX.Element;
export declare const WorkIcon: () => import("react/jsx-runtime").JSX.Element;
export declare const CalendarIcon: () => import("react/jsx-runtime").JSX.Element;
export declare const LayoutIcon: () => import("react/jsx-runtime").JSX.Element;
export declare const QuotesIcon: () => import("react/jsx-runtime").JSX.Element;
export declare const TodoIcon: () => import("react/jsx-runtime").JSX.Element;
export declare const UsersIcon: () => import("react/jsx-runtime").JSX.Element;
export declare const SuppliersIcon: () => import("react/jsx-runtime").JSX.Element;
export declare const ChatIcon: () => import("react/jsx-runtime").JSX.Element;
//# sourceMappingURL=icons.d.ts.map